### ISSUE TITLE
dbt assets get incorrectly materialized by multiple dbt runs

### ISSUE THREAD

**Issue by remigabillet** [dagster-io/dagster#13437]
### Dagster version

1.2.3

### What's the issue?

I'm on `dagster-dbt` 0.18.3 and load my dbt project with `load_assets_from_dbt_project`.

When triggering dbt asset materializations from Dagit. Dependent dbt assets sometimes get built in independent ops.

### What did you expect to happen?

I use software-defined dbt assets. I want to trigger a run by selecting dbt assets on the Dagit UI. 

![Screenshot 2023-04-07 at 12 28 19 PM](https://user-images.githubusercontent.com/20303/230593984-1053cb97-530f-4b80-bf95-68f3d6c10c55.png)

I clicked "Materialize All" on this screen. Since these assets are all defined in a single dbt project and depend on each other, I expect Dagster to trigger a single dbt run with all assets listed.

Instead, Dagster breaks up the job into 2 ops. One builds a single asset, while the other builds everything else. It's incorrect because the orphaned asset should be built after its dependencies are materialized.

![Screenshot 2023-04-07 at 12 28 35 PM](https://user-images.githubusercontent.com/20303/230594345-1ba70dee-f80a-4ab0-afd2-5e7697c74843.png)

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Interesting - it's not entirely clear to me why this would be happening. One reason that this kind of thing can happen is if there are Python assets intermixed between the dbt assets. Is that possibly the case in this situation?

cc @rexledesma to investigate deeper. @OwenKephart, who is the expert on this, will be back on April 17th and will be able to take a deeper look then.

**Comment by remigabillet** [comment]
There are Python assets upstream from the top-left asset on the UI. 
I'm open to doing more troubleshooting if you point me in the right direction. Which files should I look at?

**Comment by OwenKephart** [comment]
Hi @remigabillet ! Sorry you're running into this, it's definitely weird behavior. To the best of my knowledge, the only way this could happen is if Dagster detects a loop in your operational graph (but not your asset dependency graph).

This is for cases where there would be some dbt models that would need to execute, then some python assets that depend on those models, then some dbt models that depend on those python assets.

In order to execute this properly, you'd need to execute the first set of dbt models and the second set of dbt models in separate steps (with the python step in between).

However, because there's no non-dbt model in this view, this still shouldn't be broken up into separate ops regardless of the presence/absence of python assets. I think one of two things might be happening. Either

1. there is no situation in which execution would need be broken up, but this dependency resolution logic still thinks it should be
or
2. if you were to execute all of your assets at once (not just the ones in this view), then execution would need to be broken up, but we're incorrectly doing that in this view as well.

If (2), then I think what I'm seeing would seem to imply that the `dbt_warehouse.spider.v4.3-merge.spider_merged_experiences` model depends on some source (which is populated by a non-dbt asset), and that non-dbt asset in turn depends on another dbt asset. 

To help look into this more, is it possible to see the upstream dependencies of the spider_merged_experienced asset? Ideally a full screenshot of the asset graph would give the most information but if it's too large to render legibly or you don't want to share that in a public forum, the most relevant information is just the upstreams/downstreams of that one asset

**Comment by remigabillet** [comment]
Hi @OwenKephart, thanks for following up on this. 

Our asset graph is too big to share, but here's a subset that shows non-dbt dependencies upstream from `spider_merged_experiences`

![Screenshot 2023-04-20 at 9 58 20 AM](https://user-images.githubusercontent.com/20303/233299571-014a67e0-68f4-445f-b52a-ff1227e50cf9.png)

Looking at these dependencies, I can confirm we are in scenario 2. As you understand, I expect that dagster builds what's selected in the view and ignores upstream assets. These upstream assets are slow to build, so I group them into logical asset jobs and schedule each job serially.

**Comment by OwenKephart** [comment]
hi @remigabillet ! Thanks for the extra info, that was very helpful. Just as a quick update, I was able to replicate this and I'm pretty close to a solution.

**Comment by remigabillet** [comment]
Thanks @OwenKephart, I'm glad to hear you're close to a fix already.

**Comment by OwenKephart** [comment]
hi @remigabillet ! I just merged in a fix for this behavior, which will go out in this week's release. Now, the expected behavior is still to have two separate ops, but now there will be a dependency link between them, such that the second op will only start once the previous op has completed.

I recognize that this does not technically resolve this issue as originally stated (as we will still launch two separate dbt executions), but it does resolve the underlying correctness issue (now dependencies will always be respected), so I'm closing the issue for now. The reason that I went with this approach were:

- This was a necessary step regardless, as it fixes a bug in the op dependency graph that emerges in (but does not impact execution of) the asset job that contains all of the assets
- Adding in logic to keep track of these splits and attempt to re-merge definitions after the fact seems like a fairly large chunk of work that adds additional complexity to an already fairly-complex bit of the codepath

Thank you for your patience, and I'm happy to discuss more on this issue if the separate op executions present problems for you!

**Comment by remigabillet** [comment]
Thank you @OwenKephart. I was mainly concerned with the dependency between dbt models being lost and ending up with incorrect models. 
The added dependency between the split runs is a good solution for me. 
I'll try out 1.3.3 today to validate the bug fix.

**Comment by OwenKephart** [comment]
Unfortunately, I have to reopen this issue, as the original fix (which required generating new ops dynamically for these subsets) appears to have some unexpected side effects which results in errors for some users. Addressing this will require a bit more of a careful approach, likely along similar lines, but until that is implemented, I've reverted the original changes to prevent this new class of errors.

**Comment by remigabillet** [comment]
@OwenKephart This issue is still present for me in Dagster 1.5.1, and it's been causing me many headaches. The two main issues observed are:
- dbt models are built in the wrong order, causing consistency issues and bad data.
- dbt steps fail because of concurrent transactions in the warehouse.

Are there any leads towards a solution?

**Comment by OwenKephart** [comment]
Hi @remigabillet -- apologies that you're still running into this. fixes in this area are somewhat delicate, but I do have a work in progress branch that we're looking into validating. It's been on the backburner for a bit, but we're hoping to get it out in the next couple weeks.

In the meantime, if it's possible to break up your single `load_assets_from_dbt_...` invocation into multiple invocations (ideally targeting separate "layers" of the underlying dbt->python->dbt graph), this would definitely help reduce the likelihood that the automatic subsetting causes a problem (but I recognize that this may be difficult in practice).

**Comment by remigabillet** [comment]
Thanks for the quick follow-up @OwenKephart, I'm happy to hear that this issue hasn't been moved to the backlog. Let me know if I can help reproduce the issue, or simply try the branch on my project.

**Comment by OwenKephart** [comment]
Hi @remigabillet a fix has been merged in and will go out in next week's release

**Comment by remigabillet** [comment]
OMG! This is going to make my life so much better! I will try it and report back as soon as it comes out!

**Comment by remigabillet** [comment]
I was literally waiting for 2 pm today to install the update, but I noticed the PR is still open. I need to be patient.

**Comment by OwenKephart** [comment]
@remigabillet Ah sorry for the mixup! Not sure what happened there, I was sure that got in... Just merged this, and apologies for the extra wait.

**Comment by remigabillet** [comment]
No worries @OwenKephart, thanks for working on it!

**Comment by remigabillet** [comment]
Hi again @OwenKephart! Like last week, I was waiting for the launch and tested the fix immediately.

My first attempt behaved strangely. I selected 5 dbt assets to materialize. It split the run into 2 steps with 2 and 3 assets each: surprising but fair enough. The first step completed successfully, but the 2nd step did not start. 🤷 

![Screenshot 2023-11-16 at 15 56 45](https://github.com/dagster-io/dagster/assets/20303/83b23b77-2582-4acf-aca6-50269976b8df)

Fortunately, after trying a few more asset selections, everything works well, including the initial selection which runs as a single dbt step. Yoohoo! 🥳  

I suspect the bug above was caused by cached files needing to be updated.

Congrats, and thank you again for fixing this 🙏

**Comment by remigabillet** [comment]
The issue mentioned above (skipped dependencies) has been happening very often in my project. @OwenKephart helped me find a solution, so let me share the 1-line fix below. 🙏 

`context` needs to be passed to `to_default_asset_events()`. This will emit a `STEP_OUTPUT` event for each materialized dbt model and fix the problem. 😄 

Before:
```
@dbt_assets(manifest=dbt_manifest_path)
def dbt_warehouse(context: AssetExecutionContext, dbt_warehouse: DbtCliResource):
    for event in dbt_warehouse.cli(dbt_command, context=context).stream_raw_events():
        info = event.raw_event["info"]
        if info and info["level"]:
            context.log.log(info["level"], info["msg"])

        yield from event.to_default_asset_events(
            manifest=dbt_manifest_path,
            dagster_dbt_translator=CustomDagsterDbtTranslator(),
        )
```

After:
```
@dbt_assets(manifest=dbt_manifest_path)
def dbt_warehouse(context: AssetExecutionContext, dbt_warehouse: DbtCliResource):
    for event in dbt_warehouse.cli(dbt_command, context=context).stream_raw_events():
        info = event.raw_event["info"]
        if info and info["level"]:
            context.log.log(info["level"], info["msg"])

        yield from event.to_default_asset_events(
            manifest=dbt_manifest_path,
            dagster_dbt_translator=CustomDagsterDbtTranslator(),
            context=context, -- <----- HERE
        )
```
