### ISSUE TITLE
Partition performance issue due to size of StaticPartitionsDefinition

### ISSUE THREAD

**Issue by yuuuxt** [dagster-io/dagster#14384]
### Dagster version

1.3.5

### What's the issue?

When the size of `StaticPartitionsDefinition` is large, the time cost also increases and it is too much. 

### What did you expect to happen?

I'm expecting the time consumed for materialization does not increase when `StaticPartitionsDefinition` increases.

### How to reproduce?

Please check the [minimal example repo](https://github.com/yuuuxt/dagster_performance_check), which includes 2 assets of `return [2,3,4]`. On my laptop:

- when the asset is `3 * time-dimension`, materialization of one partition takes ~0.3s:
![image](https://github.com/dagster-io/dagster/assets/3153534/4f80308a-5364-4780-804d-aef74963b8ab)
![image](https://github.com/dagster-io/dagster/assets/3153534/6a015f98-f6e3-40c3-aea2-de63d7ca14be)

- when the asset is `5000 * time-dimension`, materialization of one partition takes ~ 1s:
![image](https://github.com/dagster-io/dagster/assets/3153534/4893f2bf-28c7-4b90-9c69-ba85a80862ae)
![image](https://github.com/dagster-io/dagster/assets/3153534/a2531f6a-c0d5-49c3-b272-4388d7be4def)

Besides, in my another test (in docker compose), it's like for a 1.3kb pickle materialization: `3 * time-dimension` takes 0.1s, while `~5000 * time-dimension` takes 3s.

### Deployment type

Local

### Deployment details

the result of example repo is from a win 10 laptop, and the "another test" is on a linux machine using docker compose.

### Additional information

https://dagster.slack.com/archives/C01U954MEER/p1684429605641439

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Hi @yuuuxt ! Thanks for the report, and the reproduction (very helpful!).

This is happening due to a quirk in the IOManager logic which is making Dagster generate all partition keys for that MultiPartitionsDefinition (so creating N*M string objects in memory) even though execution is just targeting a single one of those N*M partitions.

We're working on a series of performances improvements around this area, and so this should be fixed within the next couple of weeks.

**Comment by yuuuxt** [comment]
Checked that it hasn't been fixed in 1.3.11. Any plan for the foreseeable future? Thx.

**Comment by OwenKephart** [comment]
@yuuuxt sorry about that! I assumed that other changes had already fixed this as a byproduct, but that was not the case. Just put up a PR to solve this issue: https://github.com/dagster-io/dagster/pull/14965

**Comment by yuuuxt** [comment]
I'm afraid this needs to be reopened - just tested on 1.3.13 and the issue still exists.

**Comment by OwenKephart** [comment]
Hi, apologies for the confusion here, the change has been merged in but did not make the cut for the `1.1.13` release as I had originally intended. It will be available in the the `1.1.14` release, which will be the week after next (due to the July 4th holiday next week).
