### ISSUE TITLE
[windows] dagit wrapper script problems

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#1678]
https://dagster.slack.com/archives/CCCR6P2UR/p1566311213147600

```
Traceback (most recent call last):
  File "dagit", line 66, in <module>
    handler.start()
  File "C:\Users\tnaugle\AppData\Local\Continuum\anaconda3\envs\dagster\lib\site-packages\watchdog\tricks\__init__.py", line 147, in start
    self.process = subprocess.Popen(self.command, preexec_fn=os.setsid)
AttributeError: module 'os' has no attribute 'setsid'
```

**Comment by natekupp** [comment]
@alangenfeld this is fixed now right?

**Comment by fhusain-bridger** [comment]
Hi, I tried running this on my Windows 10 laptop and am seeing the same issue, so in the interim I am running it in an interactive docker container with a mounted volume.

**Comment by alangenfeld** [comment]
@fhusain-bridger what version of dagster/dagit are you running? Can you post the stack trace of the error you get? We believe this is fixed in more recent versions, I think `0.5.8`+.

**Comment by fhusain-bridger** [comment]
Trace and version below. Using Anaconda python 3.7.3 with a venv. I haven't had a chance to check the source but was subprocess.Popen changed to work with a lack of fork on windows?

```
(venv) (base) c:\work\temp\dagster2>dagit -f hello_world.py -n hello_world_pipeline
Traceback (most recent call last):
  File "C:\Users\cooljackal\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\cooljackal\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\work\temp\dagster2\venv\Scripts\dagit.exe\__main__.py", line 9, in <module>
  File "c:\work\temp\dagster2\venv\lib\site-packages\dagit\dagit.py", line 80, in main
    handler.start()
  File "c:\work\temp\dagster2\venv\lib\site-packages\watchdog\tricks\__init__.py", line 147, in start
    self.process = subprocess.Popen(self.command, preexec_fn=os.setsid)
AttributeError: module 'os' has no attribute 'setsid'

(venv) (base) c:\work\temp\dagster2>dagit --version

(venv) (base) c:\work\temp\dagster2>dagit, version 0.5.9
```

**Comment by alangenfeld** [comment]
Thanks for taking the time to provide that information. I mistook this issue for a different `setsid` problem.

For now you can workaround this issue by using `dagit-cli` directly instead of `dagit`.

**Comment by fhusain-bridger** [comment]
Got it. Thanks for the feedback. I am still getting weird issues with the dagit-cli tool on windows, I might be missing something while running it.

I will stick to the docker container for now as it has worked very well across PCs, and is easier for people in our team to get up and running. I would focus on issues like #1684, which we are running into as well.

Great piece of software though.
