### ISSUE TITLE
Unclear how to configure credentials for S3 Compute Logs Manager

### ISSUE THREAD

**Issue by Radiergummi** [dagster-io/dagster#25867]
### What's the issue or suggestion?

The documentation describes how to configure S3ComputeLogManager [here](https://docs.dagster.io/deployment/dagster-instance#s3computelogmanager):

> **S3ComputeLogManager**  
> The [S3ComputeLogManager](https://docs.dagster.io/_apidocs/libraries/dagster-aws#dagster_aws.s3.S3ComputeLogManager) writes stdout and stderr to an Amazon Web Services S3 bucket.
> 
> ```yaml
> # there are multiple ways to configure the S3ComputeLogManager
> 
> # you can set the config values directly:
> compute_logs:
>   module: dagster_aws.s3.compute_log_manager
>   class: S3ComputeLogManager
>   config:
>     bucket: "mycorp-dagster-compute-logs"
>     prefix: "dagster-test-"
> 
> # or grab some or all of them from environment variables
> compute_logs:
>   module: dagster_aws.s3.compute_log_manager
>   class: S3ComputeLogManager
>   config:
>     bucket:
>       env: MYCORP_DAGSTER_COMPUTE_LOGS_BUCKET
>     prefix:
>       env: DAGSTER_COMPUTE_LOG_PREFIX
> ```

That description lacks any mention of credentials for the bucket. Going further, when looking at the [API documentation](https://docs.dagster.io/_apidocs/libraries/dagster-aws#dagster_aws.s3.S3ComputeLogManager), I see this:

> Logs compute function stdout and stderr to S3.
> 
> Users should not instantiate this class directly. Instead, use a YAML block in dagster.yaml such as the following:
> 
> ```yaml
> compute_logs:
>   module: dagster_aws.s3.compute_log_manager
>   class: S3ComputeLogManager
>   config:
>     bucket: "mycorp-dagster-compute-logs"
>     local_dir: "/tmp/cool"
>     prefix: "dagster-test-"
>     use_ssl: true
>     verify: true
>     verify_cert_path: "/path/to/cert/bundle.pem"
>     endpoint_url: "http://alternate-s3-host.io"
>     skip_empty_files: true
>     upload_interval: 30
>     upload_extra_args:
>       ServerSideEncryption: "AES256"
>     show_url_only: false
>     region: "us-west-1"
> ```

Again, no mention of credentials! How is this even supposed to work? Like I upload logs to public buckets..?

Yet one step further down into parts of Dagster I never wanted to see, I'm looking at the [source code of S3ComputeLogManager](https://docs.dagster.io/_modules/dagster_aws/s3/compute_log_manager#S3ComputeLogManager) itself, and I find multiple issues:

- The connection to S3 is created from a fresh boto3 instance:
  ```python
  self._s3_session = boto3.resource(
      "s3", use_ssl=use_ssl, verify=_verify, endpoint_url=endpoint_url
  ).meta.client
  ```
  This means I can neither pass credentials to the class, nor rely on it using any other S3 resource configured elsewhere in Dagster.
- The class accepts a custom endpoint URL, but `capture_logs` builds URLs with Amazon's console URI hardcoded:
  ```python
  s3_base = f"https://s3.console.aws.amazon.com/s3/object/{self._s3_bucket}?region={self._region}"
  ```

From what I can gather, that means I need to use an `.aws-credentials` file and mount that everywhere (I have given up on trying to be sparse with secrets, all parts of Dagster seem to require all secrets anyway).  
However, this fact is mentioned nowhere, all other S3 usages suggest I should inject the configuration as environment variables in configuration, and neither the examples nor the documentation show any proper usage of the S3 compute logs manager.  
We're currently evaluating migrating to Dagster+. Stuff like this, code that nobody apparently ever tried to run, is a giant red flag and short of convincing me to drop Dagster altogether.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by slopp** [comment]
@Radiergummi thank you for providing this feedback, and apologies for the slight delay here 

We're going to work on improving the documentation here.

The `S3ComputeLogManager` is used by many of our largest customers so you should have confidence it works. In terms of the setup, here is the context our docs are currently missing: 


- Many of the interactions with S3 in Dagster are from "user code" (such as the `S3Resource` ). These interactions are typically part of dagster pipelines, and as such they run in many different places (locally, in CICD, in prod, etc). Behind the scenes, these tools all rely on boto3 and work if you have "AWS implicit auth" setup. BUT, because users are often using the code outside of, say, an AWS compute environment, we also have added the option for "AWS implicit auth" by having users reference AWS creds directly via env vars.

- In contrast, the `S3ComputeLogManager` is really only relevant in "system config" code, specifically for Dagster+ Hybrid users with a production agent installed and running _inside_ AWS. The result is that the compute log manager only supports "AWS implicit auth" at the moment. We'll certainly consider adding "AWS explicit auth" as an option, and we'll improve the documentation.

"AWS implicit auth" means running code in an environment where a boto3 session can be established without directly passing s3 credentials to the boto3 client initiation call site. In many cases, this implicit auth is established by virtue of IAM roles inherited because the code is running somewhere in AWS already.

**Comment by Klimnyk** [comment]
@Radiergummi Try this solution.

To address the credential issue, I've extended the S3ComputeLogManager with support for explicitly passing credentials (access_key and secret_key). Below is the updated class implementation along with the necessary dagster.yaml configuration.

`my_s3_log_manager.py`

``` python
import os
from contextlib import contextmanager
from typing import Any, Iterator, Mapping, Optional, Sequence
import boto3
from botocore.errorfactory import ClientError
from dagster_aws.s3.compute_log_manager import S3ComputeLogManager
from dagster import (
    Field,
    Permissive,
    StringSource,
)
from dagster._config.config_type import Noneable
from dagster._core.storage.compute_log_manager import CapturedLogContext, ComputeIOType
from dagster._serdes import ConfigurableClassData
from typing_extensions import Self

class MyS3ComputeLogManager(S3ComputeLogManager):
    """Custom class for S3ComputeLogManager with added support for accessKey and secretKey"""

    def __init__(
        self,
        bucket,
        local_dir=None,
        inst_data: Optional[ConfigurableClassData] = None,
        prefix="dagster",
        use_ssl=True,
        verify=True,
        verify_cert_path=None,
        endpoint_url=None,
        skip_empty_files=False,
        upload_interval=None,
        upload_extra_args=None,
        show_url_only=False,
        region=None,
        access_key=None, 
        secret_key=None,  
    ):
        super().__init__(
            bucket=bucket,
            local_dir=local_dir,
            inst_data=inst_data,
            prefix=prefix,
            use_ssl=use_ssl,
            verify=verify,
            verify_cert_path=verify_cert_path,
            endpoint_url=endpoint_url,
            skip_empty_files=skip_empty_files,
            upload_interval=upload_interval,
            upload_extra_args=upload_extra_args,
            show_url_only=show_url_only,
            region=region,
        )

        if access_key and secret_key:
            self._s3_session = boto3.resource(
                "s3",
                use_ssl=use_ssl,
                verify=verify if verify else verify_cert_path,
                endpoint_url=endpoint_url,
                aws_access_key_id=access_key,
                aws_secret_access_key=secret_key, 
            ).meta.client
        else:
            self._s3_session = boto3.resource(
                "s3", use_ssl=use_ssl, verify=verify if verify else verify_cert_path, endpoint_url=endpoint_url
            ).meta.client

    @classmethod
    def config_type(cls):
        return {
            "bucket": StringSource,
            "local_dir": Field(StringSource, is_required=False),
            "prefix": Field(StringSource, is_required=False, default_value="dagster"),
            "use_ssl": Field(bool, is_required=False, default_value=True),
            "verify": Field(bool, is_required=False, default_value=True),
            "verify_cert_path": Field(StringSource, is_required=False),
            "endpoint_url": Field(StringSource, is_required=False),
            "skip_empty_files": Field(bool, is_required=False, default_value=False),
            "upload_interval": Field(Noneable(int), is_required=False, default_value=None),
            "upload_extra_args": Field(
                Permissive(), is_required=False, description="Extra args for S3 file upload"
            ),
            "show_url_only": Field(bool, is_required=False, default_value=False),
            "region": Field(StringSource, is_required=False),
            "access_key": Field(StringSource, is_required=False),  
            "secret_key": Field(StringSource, is_required=False), 
        }

    @classmethod
    def from_config_value(
        cls, inst_data: ConfigurableClassData, config_value: Mapping[str, Any]
    ) -> Self:
        return cls(inst_data=inst_data, **config_value)
```

`dagster.yaml`
``` yaml
compute_logs:
  module: path/to/my_s3_log_manager
  class: MyS3ComputeLogManager
  config:
    access_key: "access_key"
    secret_key: "secret_key"
    bucket: "mycorp-dagster-compute-logs"
    local_dir: "/tmp/cool"
    prefix: "dagster-test-"
    use_ssl: true
    verify: true
    endpoint_url: "https://mini.host.io"
    skip_empty_files: true
    upload_interval: 30
    show_url_only: false
    region: "us-west-1"
```

**Comment by fboerman** [comment]
@Klimnyk where do I put this MyS3ComputeLogManager and how do I register it? Thanks in advance!

**Comment by ion-elgreco** [comment]
@slopp can you assign this to me? I want to make it compatible with any S3 store, not just aws

**Comment by ion-elgreco** [comment]
This is resolved with the release of `dagster-obstore` which supports any S3, ADLS and GCS 

Feel free to close @garethbrickman

**Comment by gabibeyer** [comment]
Is there any documentation on how to install/utilize the obstore library? Does this need to be install on the serverside, within the daemon, or is it possible to use a user deployment? We are using helm for our dagster install, and I'm not sure how to install the dagster_obstore python module.

**Comment by joshuataylor** [comment]
Unless I'm missing something, dagster-obstore will cause a warning? `UserWarning: Found version mismatch between `dagster-shared` (1.11.9) expected library version (0.27.9) and `dagster-obstore` (0.2.3).`

**Comment by joshuataylor** [comment]
Still seeing our logs swamped with:

```sh
our_dagster            | /path/to/dagster_shared/libraries/__init__.py:61: UserWarning: Found version mismatch between `dagster-shared` (1.12.2) expected library version (0.28.2) and `dagster-obstore` (0.2.3).
```

Does this need to be set as the same version?

**Comment by bobafettfrom** [comment]
anyone?
Is it ok?
our_dagster            | /path/to/dagster_shared/libraries/__init__.py:61: UserWarning: Found version mismatch between `dagster-shared` (1.12.2) expected library version (0.28.2) and `dagster-obstore` (0.2.3).
and we still can't store logs in s3 unless it's s3 aws?

**Comment by Radiergummi** [comment]
@joshuataylor, @bobafettfrom the documentation says the versions should be updated together, so even if it *probably* works, I don't see any reason to just like, do that..?

**Comment by joshuataylor** [comment]
I don't understand what you mean.

The two versions are different. Hence the error.

edit: the fix is to either check the package is dagster itself, or bump dagster-xxx packages to always match dagsters latest version.

**Comment by joshuataylor** [comment]
@ion-elgreco See https://github.com/dagster-io/dagster/issues/32869 -- what do you reckon the solution for this would be, should we propose relaxing this constraint for non-dagster projects? Or rename `dagster-obstore` to something else, so it won't trigger this?

**Comment by joshuataylor** [comment]
so there is no solution to using dagster-obs, and our error logging is now needing a filter in place if using datadog, to remove these warnings? is that the solution?

**Comment by ion-elgreco** [comment]
@joshuataylor its probably a minor fix, just open a PR to the repo
