### ISSUE TITLE
[dagster-dbt] Failure while loading manifest.json in 1.10.14 (in execution)

### ISSUE THREAD

**Issue by IsmaelRDeMelo** [dagster-io/dagster#29918]
### What's the issue?

The problem is that Dagster is failing in some way to load the manifest.json and access the key 'nodes' from it in execution, in other words when i launch a asset materialization, the dagster-dbt dbt.cli().stream() is not finding the key 'nodes' as if it isn't loading the manifest.json in execution of dbt assets.
Here's a print

![Image](https://github.com/user-attachments/assets/9fcee0b0-d25c-409d-a2f1-54d8c7f06575)

The project is loading correctly and the assets are loaded just fine, but when we launch a materialization, the error above happens everytime
Also the command executed by the CLI changes from ```dbt run --select models --profiles-dir /path -target tar``` to ```dbt run --profiles-dir /path --target tar```

### What did you expect to happen?

The expected output was that no error should've be thrown and the models should've executed just fine as it happens in 1.10.13

### How to reproduce?

It's easy, you just need to upgrade to version 1.10.14, have a dbt project configured with @dbt_assets or similar, at any point have a dbt.cli().stream() command and materialize a asset after you dagster project loads and it's avaible in localhost:3000.  

### Dagster version

1.10.14

### Deployment type

Other Docker-based deployment

### Deployment details

```CMD dagster-webserver -h 0.0.0.0 -p 8080 & dagster-daemon run``` is the final command from my Dockerfile to make the project get up. 
```

DBT_MANIFEST = Path(
    file_relative_path(__file__, "../../my-awesome-dbt-project/target/manifest.json")
)

@dbt_assets(
    manifest=DBT_MANIFEST,
    select=f"{MODELS}{MODELS_}{MODELS_D}",
    partitions_def=daily_partitions_def,
    dagster_dbt_translator=CustomDagsterDbtTranslator(settings=DagsterDbtTranslatorSettings(enable_asset_checks=True)),
    backfill_policy=BackfillPolicy.single_run(),
)
def dbt_assets(context: OpExecutionContext, dbt_resource: DbtCliResource):
    yield from _process_partitioned_dbt_assets(context=context, dbt=dbt_resource)

def _process_partitioned_dbt_assets(context: OpExecutionContext, dbt: DbtCliResource):
    # map partition key range to dbt vars
    first_partition, last_partition = context.partition_time_window
    context.log.error(context.partition_time_window)
    dbt_vars = {"min_date": str(first_partition), "max_date": str(last_partition)}
    dbt_args = ["build", "--vars", json.dumps(dbt_vars)]

    yield from dbt.cli(dbt_args, context=context).stream()



```

### Additional information

I don't think so, if you have any questions, I'll be looking at this thread daily and eager to answer them

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by whytem** [comment]
I'm also seeing this issue. Temporarily resolved by reverted back to 1.10.13

**Comment by maximearmstrong** [comment]
I was able to repro - PR #30003 will fix this issue.

**Comment by IsmaelRDeMelo** [comment]
@maximearmstrong for what I read in your PR, if we change to AssetExecutionContext it should work again in the 1.10.14, right?

**Comment by IsmaelRDeMelo** [comment]
@maximearmstrong didn't solve, just deployed my dagster to 1.10.15 and the same error happened, so I'm changing to AssetExecutionContext to see if it solves

**Comment by maximearmstrong** [comment]
@IsmaelRDeMelo the fixes has been merged after 1.10.15 was released - it will be included in 1.10.16 this Thursday.
