### ISSUE TITLE
Schedules don't run

### ISSUE THREAD

**Issue by galloramiro** [dagster-io/dagster#4190]
## Summary

I have a Dagit with 4 repositories, each with different schedules.     
Ussually the run perfectly but now the aren't runing and there is no advice, no error, no nothing.   
I'm traing localy by changin the time and waiting but nothing, traing to removing all the Dagit folders that create with history and logs, but nothing to.   
I try to find something in the issues here, or in stack overflow but nothing to, that's why I'm creating this issue.

## Reproduction

1. Create solids
2. Create pipelines
3. Create schedule
4. Create repository
5. Run dagit

## Dagit UI/UX Issue Screenshots

![Screenshot from 2021-05-19 16-32-36](https://user-images.githubusercontent.com/25160187/118873334-0316f580-b8c0-11eb-97f4-f26abe4c8acd.png)
![Screenshot from 2021-05-19 16-33-07](https://user-images.githubusercontent.com/25160187/118873342-05794f80-b8c0-11eb-8245-2cb788bd6a09.png)

## Additional Info about Your Environment

**requirements.txt**
I need to specify the `flask` and `Werkzeug` version because with the new `flask` and new `Werkzeug` I have a socket error.
```
flask==1.1.4
Werkzeug==1.0.1
dagster==0.10.5
dagit==0.10.5
dagster-cron==0.10.5
dagster-pandas==0.10.5
```
**dagster.yml**
```
scheduler:
  module: dagster_cron.cron_scheduler
  class: SystemCronScheduler

telemetry:
      enabled: false
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @galloramiro - is using our default daemon scheduler an option here? The SystemCronScheduler is deprecated (and the new scheduler has a lot more debugging information for investigating situations like this).

One possibility is that your cron system is using a different timezone than the timezone that is set on your schedule (if that's the case, switching to the default scheduler should solve that problem)

**Comment by gibsondan** [comment]
More information about the daemon process here: https://docs.dagster.io/deployment/dagster-daemon

Turning it on should be as stopping any schedules, as removing the 'scheduler' key from your dagster.yml, turning your schedules back on, and starting up the daemon process as described in those docs.

**Comment by galloramiro** [comment]
I try to move all to the dagster daemon using [this example](https://github.com/dagster-io/dagster/blob/0.11.9/examples/deploy_docker/), and Dagit recognice the tasks from the repo, but not recognice the Daemon, and the Daemon donsent recognice Dagit.   

Let me share my config. 

**docker-compose.yml**
```
version: "3.8"

services:
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    networks:
      - web
    privileged: true
    shm_size: 2G

  # This service runs the gRPC server that loads and executes your pipelines, in both dagit
  # and dagster-daemon. By setting DAGSTER_CURRENT_IMAGE to its own image, we tell the
  # run launcher to use this same image when launching runs in a new container as well.
  # Multiple containers like this can be deployed separately - each just needs to run on
  # its own port, and have its own entry in the workspace.yaml file that's loaded by dagit.
  scrappers_web_tasks:
    image: scrappers_web_tasks_image
    container_name: scrappers_web_tasks
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.tasks
    volumes:
      - ./src:/scrape_web_tasks/src
    networks:
      - web
      - dagster-network
    depends_on:
      - chrome
    extra_hosts:
      - ${MYSQL_HOST_STRING}
      - ${WAN_SERVER_IP}
  
  # This service runs dagit, which loads the pipelines from the user code container.
  # Since our instance uses the QueuedRunCoordinator, any runs submitted from dagit will be put on
  # a queue and later dequeued and launched by dagster-daemon.
  dagit:
    build:
      context: .
      dockerfile: ./Dockerfile.dagster
    entrypoint:
      - dagit
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    container_name: dagit
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes: # Make docker client accessible so we can terminate containers from dagit
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dagster-network
    depends_on:
      - scrappers_web_tasks
  
  # This service runs the dagster-daemon process, which is responsible for taking runs
  # off of the queue and launching them, as well as creating runs from schedules or sensors.
  dagster-daemon:
    image: dagster-daemon
    build:
      context: .
      dockerfile: Dockerfile.dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster_daemon
    restart: on-failure
    volumes: # Make docker client accessible so we can launch containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dagster-network
    depends_on:
      - scrappers_web_tasks

networks:
  web:
    external: true
    driver:  bridge
  dagster-network:
    driver: bridge
    name: dagster-network
```

**workspace.yml**
```
load_from:
  - grpc_server:
      host: scrappers_web_tasks
      port: 4000
      location_name: "scrappers_web_tasks"
```

**dagster.yml**
```
scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler

run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator

run_launcher:
  module: dagster_docker
  class: DockerRunLauncher
  config:
    network: dagster-network

telemetry:
      enabled: false
```

**Dockerfile.trasks**
```
FROM my_personal_image

ADD src/ src/

EXPOSE 4000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "src/task_manager/repositories.py"]
```
**Dockerfile.dagster**
```
FROM python:3.8-slim

RUN pip install \
    dagster \
    dagster-graphql \
    dagit \
    dagster-postgres \
    dagster-docker

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY src/dagster.yaml src/workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
```

**Comment by galloramiro** [comment]
Thanks for the response, you are right! 
I try and now it's working, but the shcedule still not run, I have a postgres error, Im using the test variables from the example to run this and avoid errors. 

Srry but im new with all this config hahahah

![Screenshot from 2021-05-21 12-18-53](https://user-images.githubusercontent.com/25160187/119161244-78ed9f00-ba2f-11eb-8cc4-d9250f3fea17.png)
![Screenshot from 2021-05-21 12-22-43](https://user-images.githubusercontent.com/25160187/119161258-7db25300-ba2f-11eb-8335-0d3f3c68ab70.png)

**Comment by gibsondan** [comment]
Could you post your updated docker-compose.yaml and dagster.yaml? That error message looks like the run launcher is trying to launch a run in the postgres DB container, which probably indicates that something is misconfigured.

That comment in the docker-compose file may be relevant:

"By setting DAGSTER_CURRENT_IMAGE to its own image, we tell the run launcher to use this same image when launching runs in a new container as well."

It's important that the container that you're using for your gRPC server do this, to tell the run launcher which image it should use when launching runs. Note how the example includes this line:

      DAGSTER_CURRENT_IMAGE: "docker_example_pipelines_image"

**Comment by gibsondan** [comment]
(so you might want to include DAGSTER_CURRENT_IMAGE : "scrappers_web_tasks_image" in the environment variables for your pipeline container if it isn't there already)

**Comment by galloramiro** [comment]
You are amazing, think we are almost there. 

They recognize but keep in starting the task but do not advance from there
![Screenshot from 2021-05-21 14-27-18](https://user-images.githubusercontent.com/25160187/119176219-32a13b80-ba41-11eb-9c18-37513483e924.png)

**Comment by gibsondan** [comment]
Are there logs from the container that was launched? Usually when it's stuck in starting, it means that it had trouble loading the DagsterInstance (so it couldn't write anything about why it failed).

'docker logs <container_id>' will hopefully output something useful here'

**Comment by galloramiro** [comment]
Seams the never ending story hahaha

The advice that you'll give me goes nice, I found I was missing dagster-postgres dependency.
But now dont regoncie some environment variables.
If i run the task with some shell runs that I create with typer run ok:
```
docker-compose run --rm scrappers_web_tasks python src/scrapper/shell_runs/call_center.py
```
But wen I run the task I get this error:
![Screenshot from 2021-05-21 15-29-20](https://user-images.githubusercontent.com/25160187/119182501-5ec0ba80-ba49-11eb-9c67-ce25dfbc948d.png)
I put the .env in the compose for all the serivices but still missing. :/
What I'm not seeing?

Thanks and a lot of thanks for your help!

**Comment by gibsondan** [comment]
A couple of options:

- If you use the DefaultRunLauncher rather than the DockerRunLauncher (by taking out the 'run_launcher' key from your instance yaml), it will launch the run within that same container instead of in a new container. That way it should have access to all the environment variables (but you don't get one container per run which is nice for some things)

- If you do want to use DockerRunLauncher, you need to configure it with all the environment variables as part of the run launcher config (it would be nice if there was some way to tell it to make a 'copy' of an existing service/container rather than just create a new container using the same image, but we don't have anything like that currently). Unfortunately I don't think the docker API for python has support for env files yet, so you may need to list out the environment variables individually for now (like you are currently listing DAGSTER_POSTGRES_USER etc.).

**Comment by galloramiro** [comment]
Amazing! 
Its working!!! Thanks for all the help!!! 
Hope could help you out in the near future with something!

**Comment by gibsondan** [comment]
No problem! this stuff is complicated/hard to debug when issues come up, esp when the logs don't appear in Dagit. Glad it's working!
