### ISSUE TITLE
kubernetes executor: python3: argument list too long for complex dependency graphs

### ISSUE THREAD

**Issue by kervel** [dagster-io/dagster#8314]
## Summary

I have a re-execution of a job with a complex dynamic DAG (> 1K ops, of which i 600 ran during the first try)
i'm using the kubernetes executor to launch the steps. the kubernetes executor adds a "known_state" to the list of python arguments to launch the pod:

this "known_state" object seems to be huge (3K lines) and the pod fails with:
```
exec /usr/bin/python3: argument list too long
```

## Reproduction
any job with a large enough DAG will trigger this (at least in its re-execution)

## Dagit UI/UX Issue Screenshots

![image](https://user-images.githubusercontent.com/154455/173083984-747ecb71-a5b0-4782-a467-a8473a98c7fb.png)

![image](https://user-images.githubusercontent.com/154455/173083454-ee88b4aa-e784-44f5-896e-55cf8bdfc1a8.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by johannkm** [comment]
Apologies for the delay here, this should be fixed this week

**Comment by johannkm** [comment]
Closed by https://github.com/dagster-io/dagster/pull/8564?no-redirect=1, will go out in the Thursday release

**Comment by sinnfashen** [comment]
Hi team! I initially thought I met the same problem but now I'm not that sure. The situation we were facing is pretty similar: we had a job run with 600 dynamic output ops. We saw the error message to be `exec /opt/conda/envs/akuna/bin/dagster: argument list too long`. And none of those ops can run. (One difference here might be that we don't need any re-execution to hit the error). After seeing this thread we updated our dagster to the latest one (1.0.13). Still we see the same error while I can see that `DAGSTER_EXECUTE_STEP_ARGS` is properly set as an env in the container section. 

<img width="1042" alt="Screen Shot 2022-10-17 at 9 44 49 AM" src="https://user-images.githubusercontent.com/22710431/196207999-796660a3-405a-4a0b-94f5-042d0f67b301.png">

<img width="329" alt="Screen Shot 2022-10-17 at 9 44 12 AM" src="https://user-images.githubusercontent.com/22710431/196207834-02e3cc32-1918-4e6f-9049-4021351e8eb4.png">

**Comment by sinnfashen** [comment]
@johannkm bump. Or should we better open a new issue? We followed up here mainly suspecting that we are having the same issue and after we bumping the version the fix doesn't seem to help in our case.

**Comment by juanarrivillaga** [comment]
@johannkm I am also still seeing this behavior. I've posted some information on the slack channel:

https://dagster.slack.com/archives/C014N0PK37E/p1666737017754699

Note, here is the job manifest yaml:

```
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2022-10-25T16:41:57Z"
  generateName: dagster-step-6527edf0609f7ecea00021a01b2e8350-
  labels:
    app.kubernetes.io/component: step_worker
    app.kubernetes.io/instance: dagster
    app.kubernetes.io/name: dagster
    app.kubernetes.io/part-of: dagster
    app.kubernetes.io/version: 1.0.14
    controller-uid: e2588cee-1c16-44d9-ae70-cce7842a789d
    dagster/job: ASSET_JOB
    dagster/op: etl_finngen_gwas_sumstats.download_gwas_transform_upload_parque
    dagster/run-id: ff7fff0b-ffe8-4990-b40a-c0d1631fb399
    job-name: dagster-step-6527edf0609f7ecea00021a01b2e8350
  name: dagster-step-6527edf0609f7ecea00021a01b2e8350-tzfc8
  namespace: dagster
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: dagster-step-6527edf0609f7ecea00021a01b2e8350
    uid: e2588cee-1c16-44d9-ae70-cce7842a789d
  resourceVersion: "204837656"
  uid: 347329df-ee12-427b-b6eb-e1e68a3ca8a8
spec:
  containers:
  - args:
    - dagster
    - api
    - execute_step
    env:
    - name: DAGSTER_EXECUTE_STEP_ARGS
      value: '{"__class__": "ExecuteStepArgs", "instance_ref": {"__class__": "InstanceRef",
        "compute_logs_data": {"__class__": "ConfigurableClassData", "class_name":
        "NoOpComputeLogManager", "config_yaml": "{}\n", "module_name": "dagster.core.storage.noop_compute_log_manager"},
        "custom_instance_class_data": null, "event_storage_data": {"__class__": "ConfigurableClassData",
        "class_name": "PostgresEventLogStorage", "config_yaml": "postgres_db:\n  db_name:
        test\n  hostname: dagster-postgresql\n  params: {}\n  password:\n    env:
        DAGSTER_PG_PASSWORD\n  port: 5432\n  username: test\n", "module_name": "dagster_postgres.event_log"},
        "local_artifact_storage_data": {"__class__": "ConfigurableClassData", "class_name":
        "LocalArtifactStorage", "config_yaml": "base_dir: /opt/dagster/dagster_home\n",
        "module_name": "dagster.core.storage.root"}, "run_coordinator_data": {"__class__":
        "ConfigurableClassData", "class_name": "QueuedRunCoordinator", "config_yaml":
        "{}\n", "module_name": "dagster.core.run_coordinator"}, "run_launcher_data":
        {"__class__": "ConfigurableClassData", "class_name": "K8sRunLauncher", "config_yaml":
        "dagster_home: /opt/dagster/dagster_home\nimage_pull_policy: Always\ninstance_config_map:
        dagster-instance\njob_namespace: dagster\nload_incluster_config: true\npostgres_password_secret:
        dagster-postgresql-secret\nservice_account_name: dagster\n", "module_name":
        "dagster_k8s"}, "run_storage_data": {"__class__": "ConfigurableClassData",
        "class_name": "PostgresRunStorage", "config_yaml": "postgres_db:\n  db_name:
        test\n  hostname: dagster-postgresql\n  params: {}\n  password:\n    env:
        DAGSTER_PG_PASSWORD\n  port: 5432\n  username: test\n", "module_name": "dagster_postgres.run_storage"},
        ....
        ....
```

You can see, it is being passed as an environment variable, which looking at the PR linked above seems to have been the fix. However, is it possible that somewhere after the environment variable is consumed by `click`: https://github.com/dagster-io/dagster/blob/32c316de6795187096ed88fba4ab8c01dd15f6d8/python_modules/dagster/dagster/_cli/api.py#L318 that the args are being passed via the command line (maybe in a subprocess?).

**Comment by markfickett** [comment]
I'm also running into this issue. My code location is using an image built with Dagster 1.0.13. My pipeline runs fine with 10-20 parallel steps, and then when it hits a fan-out to ~300 they error.

**Comment by johannkm** [comment]
The above fix will go out in the 1.0.16 release this Thursday

**Comment by akoumjian** [comment]
We are still experiencing this issue. We generate thousands of dynamic outs for running our large compute jobs inside k8s. Question: does `known_state` and the instance ref all really need to be serialized? Can't all that context be initialized with the database, the run_id, and the step_key_handle on start? I see that it works that way when you re-execute parts of a job.

**Comment by jrouly** [comment]
Agreed this appears to still be an issue. I have a pipeline with ~16k dynamic outs in some cases and the resulting `DAGSTER_COMPRESSED_EXECUTE_STEP_ARGS` is almost 150k characters long. Which causes almost all steps after the first handful to fail out of the gate.
